### ISSUE TITLE
Story Roadmap

### ISSUE THREAD

**Issue by xaprb** [xaprb/story#45]
A high-level roadmap for how I'd continue to develop Story, if I had lots of time and focus to invest in it. Each of the following bullet points would be a sort of theme I'd focus on improving, to add value to Story over time:

- [ ] Slideshows, speaking, upcoming conferences
- [ ] Podcasting: if you record yourself reading your blog posts and post it as a podcast, then link to each episode from each blog post, and embed an audio player inside the page too.
- [ ] Share-ability: social sharing, pull quotes, click-to-tweet
- [ ] Print and typography: pull quotes, notes, chapters, sections, asides, tips, ToC,  equation captions, multicol
- [ ] Related content, series

Each of these has quite a bit of detail in my mind; there's a lot of stuff that could be done. If you're interested in any of these, let me know and I can paste in some of my notes.

**Comment by xaprb** [comment]
I’m sorry but I’m not interested in maintaining this theme anymore. I’m glad it’s been useful, and I encourage someone to continue development elsewhere. The MIT license is very permissive and should not place any burdensome restrictions upon that.
